# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9c07a7cd7eb505d75bc0e0bf704ee2a2ea92b95fc6fe2cdb1805555c5910cc9a8a1f9294378e82c9ee1eadb2c97ec0935e8f1d0717767ffb7e4c7f459aee07a

test:
  secret_key_base: 5f081071a007b79945c0128f214758c091d340ff9e98241f7e3e81ff7a7e9b902ce2c96be2d88d88218511a44188fccbaa3a1179a14cfbe6ffac8c37abd98d04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
